services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_HOST
        value: n8n-service-jvm5.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-service-jvm5.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_OAUTH2_GOOGLE_CLIENT_ID
        value: 39695414231-bj4slepsbn6nmft69l2p75s53nv42vnk.apps.googleusercontent.com
      - key: N8N_OAUTH2_GOOGLE_CLIENT_SECRET
        value: 39695414231-bj4slepsbn6nmft69l2p75s53nv42vnk.apps.googleusercontent.com
